version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idn-location-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - idn-location-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: idn-location-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - idn-location-network

  db:
    image: mysql:8.0
    container_name: idn-location-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - idn-location-network

networks:
  idn-location-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
